assets:
  settings.xml: llorllale/home#assets/cactoos-matchers/settings.xml
  pubring.gpg: llorllale/home#assets/pubring.gpg
  secring.gpg: llorllale/home#assets/secring.gpg
docker:
  image: g4s8/rultor:alpine3.10
  as_root: true
architect:
  - llorllale
  - paulodamaso
merge:
  script: |
    pdd -f /dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
    mvn clean site -Psite --errors --settings ../settings.xml
deploy:
  script: |
    pdd -f /dev/null
    mvn clean deploy -Pqulice --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Psonar -Pqulice -Psonatype --errors --settings ../settings.xml