dist: xenial
language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - pdd --file=/dev/null
  - mvn -P site clean site --errors --batch-mode
  - mvn -P qulice clean install --errors --batch-mode
install:
  - gem install pdd
  - gem install xcop
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - openjdk8
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
