#
# The MIT License (MIT)
#
# Copyright (c) for portions of project cactoos-matchers are held by
# Yegor Bugayenko, 2017-2018, as part of project cactoos.
# All other copyright for project cactoos-matchers are held by
# George Aristy, 2018.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        # @todo #83:30min Add windows-2019 to the test matrix after fixing quite a few errors happening on windows.
        #  Don't forget to add it to the list of required status checks in the repo's settings.
        #  See errors in the build log: https://github.com/llorllale/cactoos-matchers/runs/1082946792.
        os: [ubuntu-18.04, macOS-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: mvn clean test
      - name: CodeCov
        uses: codecov/codecov-action@v1.0.13
        if: matrix.os == 'ubuntu-18.04' && github.repository == 'llorllale/cactoos-matchers'
        timeout-minutes: 10
        with:
          file: target/coverage/jacoco.xml

  lint:
    name: Linters
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install pdd, xcop
        run: |
          gem install pdd
          gem install xcop
      - name: JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Puzzles
        run: pdd --file=/dev/null
      - name: Qulice
        run: mvn -P qulice clean install -DskipTests=true --errors --batch-mode
      - name: Site
        run: mvn -P site clean site --errors --batch-mode
